/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mega_des_mineures;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author guilh
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        panneau_grille.setVisible(false);
        infos.setVisible(false);
        stop.setVisible(false);
        Drapeaux.setVisible(false);
        infovie.setVisible(false);
        for (int i = 0; i < 26; i++) {
            for (int j = 0; j < 26; j++) {
                //CelluleGraphique cellGraph = new CelluleGraphique(plateau.grille[i][j]);
                //Grille.add(cellGraph);
            }
        }
    }

    private int dif;
    private int life = 3; //variable definissant le nombre de vie avec lesquelles le joueur debute la partie
    private int life_partie = 3;//variable qui sera modifiee lorsque le joueur perd une vie

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difficulté = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        facile = new javax.swing.JButton();
        moyen = new javax.swing.JButton();
        difficile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vie = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        panneau_grille = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Drapeaux = new javax.swing.JLabel();
        infos = new javax.swing.JLabel();
        stop = new javax.swing.JButton();
        infovie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 670));
        setMinimumSize(new java.awt.Dimension(400, 670));
        setPreferredSize(new java.awt.Dimension(525, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Difficulté.setBackground(new java.awt.Color(255, 255, 255));
        Difficulté.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("Bienvenue sur le méga-démineur !\n\n");

        jLabel2.setText("Choisissez une difficulté :");

        facile.setBackground(new java.awt.Color(255, 255, 0));
        facile.setForeground(new java.awt.Color(0, 0, 0));
        facile.setText("Facile");
        facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facileActionPerformed(evt);
            }
        });

        moyen.setBackground(new java.awt.Color(255, 153, 0));
        moyen.setForeground(new java.awt.Color(0, 0, 0));
        moyen.setText("Moyen");
        moyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moyenActionPerformed(evt);
            }
        });

        difficile.setBackground(new java.awt.Color(255, 0, 0));
        difficile.setForeground(new java.awt.Color(0, 0, 0));
        difficile.setText("Difficile");
        difficile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                difficileMouseClicked(evt);
            }
        });
        difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("10x10");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("20x20");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("30x30");

        vie.setBackground(new java.awt.Color(51, 255, 0));
        vie.setForeground(new java.awt.Color(0, 0, 0));
        vie.setText("3 vies");
        vie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DifficultéLayout = new javax.swing.GroupLayout(Difficulté);
        Difficulté.setLayout(DifficultéLayout);
        DifficultéLayout.setHorizontalGroup(
            DifficultéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifficultéLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DifficultéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(DifficultéLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(vie))
                    .addGroup(DifficultéLayout.createSequentialGroup()
                        .addComponent(facile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(moyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(difficile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DifficultéLayout.setVerticalGroup(
            DifficultéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifficultéLayout.createSequentialGroup()
                .addGroup(DifficultéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DifficultéLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(DifficultéLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(vie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DifficultéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facile)
                    .addComponent(jLabel4)
                    .addComponent(moyen)
                    .addComponent(jLabel5)
                    .addComponent(difficile)
                    .addComponent(jLabel6))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(Difficulté, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 400, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Méga-Démineur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 400, 70));

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setMinimumSize(new java.awt.Dimension(400, 400));
        panneau_grille.setName(""); // NOI18N
        panneau_grille.setPreferredSize(new java.awt.Dimension(400, 400));
        panneau_grille.setLayout(new java.awt.GridLayout(10, 10));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        Drapeaux.setText("jLabel7");

        infos.setText("jLabel7");

        stop.setText("Stopper la partie");
        stop.setActionCommand("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        infovie.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Drapeaux)
                        .addGap(26, 26, 26)
                        .addComponent(stop)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(infovie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Drapeaux)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infovie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(infos)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 350, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facileActionPerformed
        panneau_grille.setVisible(true);
        stop.setVisible(true);
        Difficulté.setVisible(false);
        vie.setVisible(false);
        if (life == 3) {
            infovie.setText(life + " vies");
        } else {
            infovie.setText(life + " vie");
        }
        life_partie = life;//on remet le nombre de vie adequat si le joueur en a perdu dans la partie d'avant.
        infovie.setVisible(true);
        dif = 1;
        initialiser_partie(dif);


    }//GEN-LAST:event_facileActionPerformed

    private void moyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moyenActionPerformed
        panneau_grille.setVisible(true);
        stop.setVisible(true);
        Difficulté.setVisible(false);
        vie.setVisible(false);
        if (life == 3) {
            infovie.setText(life + " vies");
        } else {
            infovie.setText(life + " vie");
        }
        life_partie = life;//on remet le nombre de vie adequat si le joueur en a perdu dans la partie d'avant.
        infovie.setVisible(true);
        dif = 2;
        initialiser_partie(dif);
    }//GEN-LAST:event_moyenActionPerformed

    private void difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficileActionPerformed
        panneau_grille.setVisible(true);
        stop.setVisible(true);
        Difficulté.setVisible(false);
        dif = 3;
        vie.setVisible(false);
        if (life == 3) {
            infovie.setText(life + " vies");
        } else {
            infovie.setText(life + " vie");
        }
        life_partie = life;//on remet le nombre de vie adequat si le joueur en a perdu dans la partie d'avant.
        infovie.setVisible(true);
        initialiser_partie(dif);
    }//GEN-LAST:event_difficileActionPerformed

    private void difficileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_difficileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_difficileMouseClicked

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        panneau_grille.setVisible(false);
        stop.setVisible(false);
        panneau_grille.removeAll();
        Difficulté.setVisible(true);
        Drapeaux.setVisible(false);
        infos.setVisible(false);
        vie.setVisible(true);
        infovie.setVisible(false);
    }//GEN-LAST:event_stopActionPerformed

    private void vieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieActionPerformed
        if (life == 3) {
            life = 1;
            life_partie = 1;
            vie.setText("1 vie");
            vie.setBackground(Color.red);
        } else if (life == 1) {
            life = 3;
            life_partie = 3;
            vie.setText("3 vies");
            vie.setBackground(Color.green);
        }
    }//GEN-LAST:event_vieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    public void initialiser_partie(int a) {

        Grille plateau = new Grille(a);
        int nb_case = 0;
        int nb_bombes = 0;
        if (a == 1) {
            nb_case = 10;
        }
        if (a == 2) {
            nb_case = 20;

        } else if (a == 3) {
            nb_case = 30;
        }

        panneau_grille.setLayout(new java.awt.GridLayout(nb_case, nb_case));

        panneau_grille.setPreferredSize(new Dimension(nb_case * 15, nb_case * 15));
        panneau_grille.setMinimumSize(new Dimension(nb_case * 15, nb_case * 15));
        for (int i = 0; i < nb_case; i++) {
            for (int j = 0; j < nb_case; j++) {
                plateau.grille[i][j] = new Cellule();
                if (plateau.grille[i][j].placerBombe()) {
                    nb_bombes += 1;
                }

                CelluleGraphique cellGraph = new CelluleGraphique(plateau.grille[i][j]);
                cellGraph.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent evt) {
                        Cellule cell = cellGraph.celluleAssociee;
                        if (plateau.isPartieFinie() == false) {
                            if (evt.getButton() == MouseEvent.BUTTON3) { //si on fait un clic droit
                                if (plateau.isPremierCoup() == false && cell.isCache() == true) {//si la partie n'est pas finie et que la case n'est pas demasquee
                                    if (cell.PresenceDrapeau()) {
                                        cell.enleverDrapeau();
                                        plateau.setNb_drapeaux(plateau.getNb_drapeaux() + 1);//on redonne un drapeau au joueur
                                        Drapeaux.setText("Drapeaux: " + plateau.getNb_drapeaux());
                                        Drapeaux.repaint();
                                        panneau_grille.repaint();
                                        infos.setVisible(false);

                                    } else {
                                        if (plateau.getNb_drapeaux() == 0) {
                                            infos.setText("Récupérez un drapeau pour continuer.");
                                            infos.setVisible(true);
                                        } else {
                                            cell.placerDrapeau();
                                            plateau.setNb_drapeaux(plateau.getNb_drapeaux() - 1);
                                            Drapeaux.setText("Drapeaux: " + plateau.getNb_drapeaux());
                                            Drapeaux.repaint();
                                            cellGraph.repaint();
                                            infos.setVisible(false);
                                            if (plateau.getNb_drapeaux() == 0) {
                                                if (plateau.partieGagnante()) {
                                                    plateau.setPartieFinie(true);
                                                    infos.setText("Partie gagnée.");

                                                    infos.setVisible(true);
                                                }

                                            }
                                        }
                                    }
                                }
                            }
                            if (evt.getButton() == MouseEvent.BUTTON1) { //si on fait un clic gauche
                                if (cell.isCache() && cell.PresenceDrapeau() == false) {
                                    infos.setVisible(false);
                                    if (plateau.isPremierCoup()) { //si c'est le premier coup
                                        if (cell.PresenceBombe()) {
                                            cell.enleverBombe();//si des le premier coup le joueur tombe sur une bombe, on l'enleve
                                            plateau.setNb_drapeaux(plateau.getNb_drapeaux() - 1);//et on enleve un drapeau;
                                        }
                                        plateau.setPremierCoup(false);//et on precise que le premier coup a ete joue

                                        cell.setCache(false);//on decache la case

                                        plateau.setNb_drapeaux(plateau.getNb_drapeaux() - plateau.enleverBombesPremierCoup());//et on enleve les bombes des cases autour
                                        cell.setBombeAutour(0);

                                        plateau.demasquerCases();
                                        panneau_grille.repaint();
                                        Drapeaux.setText("Drapeaux :" + plateau.getNb_drapeaux());
                                        Drapeaux.repaint();
                                        Drapeaux.setVisible(true);
                                    } else {
                                        if (cell.PresenceBombe()) {
                                            life_partie--;//le joueur perd une vie
                                            if (life_partie == 0) {
                                                infovie.setText("0 vie");
                                                infovie.repaint();
                                                plateau.setPartieFinie(true);
                                                infos.setText("Vous avez perdu.");
                                                plateau.demasquerBombes();
                                                infos.repaint();
                                                infos.setVisible(true);
                                            } else { //si il reste des vies au joueur
                                                if (life_partie != 1) {
                                                    infovie.setText(life_partie + " vies");
                                                } else {
                                                    infovie.setText(life_partie + " vie");
                                                }
                                                infovie.repaint();
                                                cell.setCache(false);
                                                //une bombe a explose donc on a besoin d'un drapeau en moins
                                                plateau.setNb_drapeaux(plateau.getNb_drapeaux() - 1);
                                                Drapeaux.setText("Drapeaux: " + plateau.getNb_drapeaux());
                                                Drapeaux.repaint();
                                                infos.setText("boum.");
                                                infos.repaint();
                                                infos.setVisible(true);
                                            }
                                        } else {
                                            if (cell.getBombeAutour() != 0) {
                                                cell.setCache(false);
                                            } else {
                                                cell.setCache(false);
                                                plateau.demasquerCases();

                                            }
                                        }
                                        panneau_grille.repaint();

                                    }
                                }
                            }
                        }
                    }
                });
                panneau_grille.add(cellGraph);
            }
            panneau_grille.repaint();
        }
        plateau.setNb_drapeaux(nb_bombes);
        Drapeaux.setText("Drapeaux: " + plateau.getNb_drapeaux());
        for (int i = 0; i < nb_case; i++) {
            for (int j = 0; j < nb_case; j++) {
                plateau.grille[i][j].setBombeAutour(plateau.nbBombesAutour(i, j));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Difficulté;
    private javax.swing.JLabel Drapeaux;
    private javax.swing.JButton difficile;
    private javax.swing.JButton facile;
    private javax.swing.JLabel infos;
    private javax.swing.JLabel infovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moyen;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JButton stop;
    private javax.swing.JToggleButton vie;
    // End of variables declaration//GEN-END:variables
}
